cryptoOneRemote/config/routes.rb
CryptoOneRemote::Application.routes.draw do
  get "session/login"
  get "session/logout"
  resources :secret_keys

  resources :roles ,:defaults => { :format => :json }

  resources :authority_keys ,:defaults => { :format => :json }

  resources :sym_keys,:defaults => { :format => :json }

  resources :groups ,:defaults => { :format => :json }

  resources :menberships ,:defaults => { :format => :json }

  resources :signatures ,:defaults => { :format => :json }

  resources :documents,:defaults => { :format => :json }

  resources :keypairs,:defaults => { :format => :json }

  resources :shared_documents ,:defaults => { :format => :json }

  resources :users,:defaults => { :format => :json }

  resources :people,:defaults => { :format => :json }

  get     'users/:owner_id/documents'  => 'documents#index'

  get     'groups/:group_id/menberships' => 'menberships#index'
  get     'users/:user_id/menberships'  => 'menberships#index'

  get     'users/:admin_id/groups' => 'groups#index'

  get     'users/:user_id/shared_documents' => 'shared_documents#index'
  get     'groups/:group_id/shared_documents' => 'shared_documents#index'
  get     'documents/:document_id/shared_documents' => 'shared_documents#index'

  get     'authority' => 'users#get_authority'

  get      'users/:signority_id/signatures' => 'signatures#index'

  post    '/login'    => 'session#login'
  get      '/logout'  => 'session#logout'

  delete  '/all'  => 'session#boom'

end

cryptoOneRemote/app/models/document.rb
class Document < ActiveRecord::Base


end

cryptoOneRemote/app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
    if  params[:owner_id]
      owner_id = params[:owner_id].to_i
      @documents= @documents.select{|doc| doc.ownerId == owner_id };
    end

    render :json => @documents
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
     render :json => @document
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
       # format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render json: @document }
      else
        format.html { render action: 'new' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    #  if shared document exit set the  ownerdId on 0
    #  if not delete the document

    shared_documents = SharedDocument.all.select{ |sharedDoc| sharedDoc.documentId == @document.id}
    if shared_documents.count>0
      @document.ownerId=0;
    else
      @document.destroy
    end
    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:symKey, :ownerId, :name, :path, :uploadDate, :hashcode)
    end
end

cryptoOneRemote/app/helpers/documents_helper.rb
module DocumentsHelper
end

cryptoOneRemote/app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :symKey %><br>
    <%= f.text_field :symKey %>
  </div>
  <div class="field">
    <%= f.label :ownerId %><br>
    <%= f.number_field :ownerId %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :path %><br>
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :uploadDate %><br>
    <%= f.date_select :uploadDate %>
  </div>
  <div class="field">
    <%= f.label :hashcode %><br>
    <%= f.text_field :hashcode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cryptoOneRemote/app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

cryptoOneRemote/app/views/documents/index.html.erb
<h1>Listing documents</h1>

<table>
  <thead>
    <tr>
      <th>Symkey</th>
      <th>Ownerid</th>
      <th>Name</th>
      <th>Path</th>
      <th>Uploaddate</th>
      <th>Hashcode</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.symKey %></td>
        <td><%= document.ownerId %></td>
        <td><%= document.name %></td>
        <td><%= document.path %></td>
        <td><%= document.uploadDate %></td>
        <td><%= document.hashcode %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

cryptoOneRemote/app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

cryptoOneRemote/app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Symkey:</strong>
  <%= @document.symKey %>
</p>

<p>
  <strong>Ownerid:</strong>
  <%= @document.ownerId %>
</p>

<p>
  <strong>Name:</strong>
  <%= @document.name %>
</p>

<p>
  <strong>Path:</strong>
  <%= @document.path %>
</p>

<p>
  <strong>Uploaddate:</strong>
  <%= @document.uploadDate %>
</p>

<p>
  <strong>Hashcode:</strong>
  <%= @document.hashcode %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>