cryptoOneRemote/config/routes.rb
CryptoOneRemote::Application.routes.draw do
  get "session/login"
  get "session/logout"
  resources :secret_keys

  resources :roles ,:defaults => { :format => :json }

  resources :authority_keys ,:defaults => { :format => :json }

  resources :sym_keys,:defaults => { :format => :json }

  resources :groups ,:defaults => { :format => :json }

  resources :menberships ,:defaults => { :format => :json }

  resources :signatures ,:defaults => { :format => :json }

  resources :documents,:defaults => { :format => :json }

  resources :keypairs,:defaults => { :format => :json }

  resources :shared_documents ,:defaults => { :format => :json }

  resources :users,:defaults => { :format => :json }

  resources :people,:defaults => { :format => :json }

  get     'users/:owner_id/documents'  => 'documents#index'

  get     'groups/:group_id/menberships' => 'menberships#index'
  get     'users/:user_id/menberships'  => 'menberships#index'

  get     'users/:admin_id/groups' => 'groups#index'

  get     'users/:user_id/shared_documents' => 'shared_documents#index'
  get     'groups/:group_id/shared_documents' => 'shared_documents#index'
  get     'documents/:document_id/shared_documents' => 'shared_documents#index'

  get     'authority' => 'users#get_authority'

  get      'users/:signority_id/signatures' => 'signatures#index'

  post    '/login'    => 'session#login'
  get      '/logout'  => 'session#logout'

  delete  '/all'  => 'session#boom'

end

cryptoOneRemote/app/models/authority_key.rb
class AuthorityKey < ActiveRecord::Base
end

cryptoOneRemote/app/models/document.rb
class Document < ActiveRecord::Base


end

cryptoOneRemote/app/models/group.rb
class Group < ActiveRecord::Base

  def deleteAllRelatedData

  end
end

cryptoOneRemote/app/models/menbership.rb
class Menbership < ActiveRecord::Base

  def to_json(options)
   result = {};
   result= {
        "id" => id,
        "user" => User.find(self.userId) ,
        "group" =>Group.find(self.groupId),
        "encryptedKGV" => encryptedKGV ,
        "admissionDate" => admissionDate
    }
  end

  def as_json( options)
    result = {};
    result= {
        "id" => id,
        "user" => User.find(self.userId) ,
        "group" =>Group.find(self.groupId),
        "encryptedKGV" => encryptedKGV ,
        "admissionDate" => admissionDate
    }

  end
end

cryptoOneRemote/app/models/person.rb
class Person < ActiveRecord::Base
  ActiveRecord::Base.include_root_in_json = false;
end

cryptoOneRemote/app/models/role.rb
class Role < ActiveRecord::Base
end

cryptoOneRemote/app/models/secret_key.rb
class SecretKey < ActiveRecord::Base
end

cryptoOneRemote/app/models/shared_document.rb
class SharedDocument < ActiveRecord::Base
  def as_json(options)
    {
        "id" => id,
        "group" => Group.find(groupId),
	      "document" => Document.find(documentId),
        "owner" => User.find(ownerId),
	      "sharingDate" =>sharingDate,
	      "encryptedSymKey" => encryptedSymKey
    }

  end

  def to_json(options)
    {
        "id" => id,
        "group" => Group.find(groupId),
        "document" => Document.find(documentId),
        "owner" => User.find(ownerId),
        "sharingDate" =>sharingDate,
        "encryptedSymKey" => encryptedSymKey
    }

  end
end

cryptoOneRemote/app/models/signature.rb
class Signature < ActiveRecord::Base
  def to_json(options)
    {	  "id"  =>id,
        "signority" => User.find(signorityId),
        "user" =>User.find(userId),
        "value"=> value,
        "encryptedPublicKey" =>encryptedPublicKey,
        "signatureDate"=>signatureDate
    }
  end

  def as_json(options)
    {	  "id"  =>id,
         "signority" => User.find(signorityId),
         "user" =>User.find(userId),
         "value"=> value,
         "encryptedPublicKey" =>encryptedPublicKey,
         "signatureDate"=>signatureDate
    }
  end
end

cryptoOneRemote/app/models/token.rb
class Token < ActiveRecord::Base
end

cryptoOneRemote/app/models/user.rb
class User < ActiveRecord::Base
  serialize :proof ,Hash
end

cryptoOneRemote/app/controllers/shared_documents_controller.rb
class SharedDocumentsController < ApplicationController
  before_action :set_shared_document, only: [:show, :edit, :update, :destroy]

  # GET /shared_documents
  # GET /shared_documents.json
  def index
    @shared_documents = SharedDocument.all

    if  params[:group_id]
      group_id = params[:group_id].to_i
      @shared_documents= @shared_documents.select{|doc| doc.groupId == group_id };
    end

    if  params[:document_id]
      document_id = params[:document_id].to_i
      @shared_documents= @shared_documents.select{|doc| doc.documentId == document_id };
    end

    if  params[:owner_id]
      document_id = params[:owner_id].to_i
      @shared_documents= @shared_documents.select{|doc| doc.ownerId == owner_id };
    end
=begin
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @shared_documents }
    end
=end

     render  :json => @shared_documents.to_json


  end

  # GET /shared_documents/1
  # GET /shared_documents/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @shared_document }
    end
  end

  # GET /shared_documents/new
  def new
    @shared_document = SharedDocument.new
  end

  # GET /shared_documents/1/edit
  def edit
  end

  # POST /shared_documents
  # POST /shared_documents.json
  def create
    @shared_document = SharedDocument.new(shared_document_params)

    respond_to do |format|
      if @shared_document.save
       # format.html { redirect_to @shared_document, notice: 'Shared document was successfully created.' }
        format.json { render json:  @shared_document.to_json({}) }
      else
        format.html { render action: 'new' }
        format.json { render json: @shared_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shared_documents/1
  # PATCH/PUT /shared_documents/1.json
  def update
    respond_to do |format|
      if @shared_document.update(shared_document_params)
        format.html { redirect_to @shared_document, notice: 'Shared document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shared_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shared_documents/1
  # DELETE /shared_documents/1.json
  def destroy
    @shared_document.destroy
    respond_to do |format|
      format.html { redirect_to shared_documents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shared_document
      @shared_document = SharedDocument.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shared_document_params
      params.require(:shared_document).permit(:groupId, :documentId, :ownerId , :sharingDate, :encryptedSymKey)
    end
end

cryptoOneRemote/app/helpers/application_helper.rb
module ApplicationHelper
end

cryptoOneRemote/app/helpers/documents_helper.rb
module DocumentsHelper
end

cryptoOneRemote/app/helpers/groups_helper.rb
module GroupsHelper
end

cryptoOneRemote/app/helpers/menberships_helper.rb
module MenbershipsHelper
end

cryptoOneRemote/app/helpers/people_helper.rb
module PeopleHelper
end

cryptoOneRemote/app/helpers/roles_helper.rb
module RolesHelper
end

cryptoOneRemote/app/helpers/secret_keys_helper.rb
module SecretKeysHelper
end

cryptoOneRemote/app/helpers/session_helper.rb
module SessionHelper
end

cryptoOneRemote/app/helpers/shared_documents_helper.rb
module SharedDocumentsHelper
end

cryptoOneRemote/app/helpers/signatures_helper.rb
module SignaturesHelper
end

cryptoOneRemote/app/helpers/users_helper.rb
module UsersHelper
end

cryptoOneRemote/app/views/shared_documents/_form.html.erb
<%= form_for(@shared_document) do |f| %>
  <% if @shared_document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shared_document.errors.count, "error") %> prohibited this shared_document from being saved:</h2>

      <ul>
      <% @shared_document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :groupId %><br>
    <%= f.number_field :groupId %>
  </div>
  <div class="field">
    <%= f.label :documentId %><br>
    <%= f.number_field :documentId %>
  </div>
  <div class="field">
    <%= f.label :sharingDate %><br>
    <%= f.date_select :sharingDate %>
  </div>
  <div class="field">
    <%= f.label :encryptedSymKey %><br>
    <%= f.text_area :encryptedSymKey %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cryptoOneRemote/app/views/shared_documents/edit.html.erb
<h1>Editing shared_document</h1>

<%= render 'form' %>

<%= link_to 'Show', @shared_document %> |
<%= link_to 'Back', shared_documents_path %>

cryptoOneRemote/app/views/shared_documents/index.html.erb
<h1>Listing shared_documents</h1>

<table>
  <thead>
    <tr>
      <th>Groupid</th>
      <th>Documentid</th>
      <th>Sharingdate</th>
      <th>Encryptedsymkey</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shared_documents.each do |shared_document| %>
      <tr>
        <td><%= shared_document.groupId %></td>
        <td><%= shared_document.documentId %></td>
        <td><%= shared_document.sharingDate %></td>
        <td><%= shared_document.encryptedSymKey %></td>
        <td><%= link_to 'Show', shared_document %></td>
        <td><%= link_to 'Edit', edit_shared_document_path(shared_document) %></td>
        <td><%= link_to 'Destroy', shared_document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shared document', new_shared_document_path %>

cryptoOneRemote/app/views/shared_documents/new.html.erb
<h1>New shared_document</h1>

<%= render 'form' %>

<%= link_to 'Back', shared_documents_path %>

cryptoOneRemote/app/views/shared_documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Groupid:</strong>
  <%= @shared_document.groupId %>
</p>

<p>
  <strong>Documentid:</strong>
  <%= @shared_document.documentId %>
</p>

<p>
  <strong>Sharingdate:</strong>
  <%= @shared_document.sharingDate %>
</p>

<p>
  <strong>Encryptedsymkey:</strong>
  <%= @shared_document.encryptedSymKey %>
</p>

<%= link_to 'Edit', edit_shared_document_path(@shared_document) %> |
<%= link_to 'Back', shared_documents_path %>