cryptoOneRemote/config/routes.rb
CryptoOneRemote::Application.routes.draw do
  get "session/login"
  get "session/logout"
  resources :secret_keys

  resources :roles ,:defaults => { :format => :json }

  resources :authority_keys ,:defaults => { :format => :json }

  resources :sym_keys,:defaults => { :format => :json }

  resources :groups ,:defaults => { :format => :json }

  resources :menberships ,:defaults => { :format => :json }

  resources :signatures ,:defaults => { :format => :json }

  resources :documents,:defaults => { :format => :json }

  resources :keypairs,:defaults => { :format => :json }

  resources :shared_documents ,:defaults => { :format => :json }

  resources :users,:defaults => { :format => :json }

  resources :people,:defaults => { :format => :json }

  get     'users/:owner_id/documents'  => 'documents#index'

  get     'groups/:group_id/menberships' => 'menberships#index'
  get     'users/:user_id/menberships'  => 'menberships#index'

  get     'users/:admin_id/groups' => 'groups#index'

  get     'users/:user_id/shared_documents' => 'shared_documents#index'
  get     'groups/:group_id/shared_documents' => 'shared_documents#index'
  get     'documents/:document_id/shared_documents' => 'shared_documents#index'

  get     'authority' => 'users#get_authority'

  get      'users/:signority_id/signatures' => 'signatures#index'

  post    '/login'    => 'session#login'
  get      '/logout'  => 'session#logout'

  delete  '/all'  => 'session#boom'

end

cryptoOneRemote/app/models/menbership.rb
class Menbership < ActiveRecord::Base

  def to_json(options)
   result = {};
   result= {
        "id" => id,
        "user" => User.find(self.userId) ,
        "group" =>Group.find(self.groupId),
        "encryptedKGV" => encryptedKGV ,
        "admissionDate" => admissionDate
    }
  end

  def as_json( options)
    result = {};
    result= {
        "id" => id,
        "user" => User.find(self.userId) ,
        "group" =>Group.find(self.groupId),
        "encryptedKGV" => encryptedKGV ,
        "admissionDate" => admissionDate
    }

  end
end

cryptoOneRemote/app/controllers/menberships_controller.rb
class MenbershipsController < ApplicationController
  before_action :set_menbership, only: [:show, :edit, :update, :destroy]

  # GET /menberships
  # GET /menberships.json
  def index
    @menberships = Menbership.all

    if  params[:user_id]
      user_id = params[:user_id].to_i
      @menberships= @menberships.select{|menber| menber.userId == user_id };
    end

    if  params[:group_id]
      group_id = params[:group_id].to_i
      @menberships= @menberships.select{|menber| menber.groupId == group_id };
    end
=begin
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @menberships }
    end
=end

      render :json => @menberships


  end

  # GET /menberships/1
  # GET /menberships/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @menbership }
    end
  end

  # GET /menberships/new
  def new
    @menbership = Menbership.new
  end

  # GET /menberships/1/edit
  def edit
  end

  # POST /menberships
  # POST /menberships.json
  def create
    @menbership = Menbership.new(menbership_params)

    respond_to do |format|
      if @menbership.save
        #format.html { redirect_to @menbership, notice: 'Menbership was successfully created.' }
        format.json { render json: @menbership.to_json({}) }
      else
        format.html { render action: 'new' }
        format.json { render json: @menbership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menberships/1
  # PATCH/PUT /menberships/1.json
  def update
    respond_to do |format|
      if @menbership.update(menbership_params)
        format.html { redirect_to @menbership, notice: 'Menbership was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @menbership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menberships/1
  # DELETE /menberships/1.json
  def destroy
    @menbership.destroy
    respond_to do |format|
      format.html { redirect_to menberships_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menbership
      @menbership = Menbership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menbership_params
      params.require(:menbership).permit(:userId, :groupId, :encryptedKGV, :admissionDate)
    end
end

cryptoOneRemote/app/helpers/menberships_helper.rb
module MenbershipsHelper
end

cryptoOneRemote/app/views/menberships/_form.html.erb
<%= form_for(@menbership) do |f| %>
  <% if @menbership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menbership.errors.count, "error") %> prohibited this menbership from being saved:</h2>

      <ul>
      <% @menbership.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userId %><br>
    <%= f.number_field :userId %>
  </div>
  <div class="field">
    <%= f.label :groupId %><br>
    <%= f.number_field :groupId %>
  </div>
  <div class="field">
    <%= f.label :encryptedKGV %><br>
    <%= f.text_field :encryptedKGV %>
  </div>
  <div class="field">
    <%= f.label :admissionDate %><br>
    <%= f.date_select :admissionDate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cryptoOneRemote/app/views/menberships/edit.html.erb
<h1>Editing menbership</h1>

<%= render 'form' %>

<%= link_to 'Show', @menbership %> |
<%= link_to 'Back', menberships_path %>

cryptoOneRemote/app/views/menberships/index.html.erb
<h1>Listing menberships</h1>

<table>
  <thead>
    <tr>
      <th>Userid</th>
      <th>Groupid</th>
      <th>Encryptedkgv</th>
      <th>Admissiondate</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @menberships.each do |menbership| %>
      <tr>
        <td><%= menbership.userId %></td>
        <td><%= menbership.groupId %></td>
        <td><%= menbership.encryptedKGV %></td>
        <td><%= menbership.admissionDate %></td>
        <td><%= link_to 'Show', menbership %></td>
        <td><%= link_to 'Edit', edit_menbership_path(menbership) %></td>
        <td><%= link_to 'Destroy', menbership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menbership', new_menbership_path %>

cryptoOneRemote/app/views/menberships/new.html.erb
<h1>New menbership</h1>

<%= render 'form' %>

<%= link_to 'Back', menberships_path %>

cryptoOneRemote/app/views/menberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userid:</strong>
  <%= @menbership.userId %>
</p>

<p>
  <strong>Groupid:</strong>
  <%= @menbership.groupId %>
</p>

<p>
  <strong>Encryptedkgv:</strong>
  <%= @menbership.encryptedKGV %>
</p>

<p>
  <strong>Admissiondate:</strong>
  <%= @menbership.admissionDate %>
</p>

<%= link_to 'Edit', edit_menbership_path(@menbership) %> |
<%= link_to 'Back', menberships_path %>